///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RegressionTest_v1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RegressionTest_v1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("884d9529-5e9e-4eae-bbdb-1b98d9ece18a")]
    public partial class RegressionTest_v1Repository : RepoGenBaseFolder
    {
        static RegressionTest_v1Repository instance = new RegressionTest_v1Repository();
        RegressionTest_v1RepositoryFolders.DashboardFinanceAndOperationsAppFolder _dashboardfinanceandoperations;

        /// <summary>
        /// Gets the singleton class instance representing the RegressionTest_v1Repository element repository.
        /// </summary>
        [RepositoryFolder("884d9529-5e9e-4eae-bbdb-1b98d9ece18a")]
        public static RegressionTest_v1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RegressionTest_v1Repository() 
            : base("RegressionTest_v1Repository", "/", null, 0, false, "884d9529-5e9e-4eae-bbdb-1b98d9ece18a", ".\\RepositoryImages\\RegressionTest_v1Repository884d9529.rximgres")
        {
            _dashboardfinanceandoperations = new RegressionTest_v1RepositoryFolders.DashboardFinanceAndOperationsAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("884d9529-5e9e-4eae-bbdb-1b98d9ece18a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The DashboardFinanceAndOperations folder.
        /// </summary>
        [RepositoryFolder("be0234f2-9cd6-45e1-8197-580f1e1ad21e")]
        public virtual RegressionTest_v1RepositoryFolders.DashboardFinanceAndOperationsAppFolder DashboardFinanceAndOperations
        {
            get { return _dashboardfinanceandoperations; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class RegressionTest_v1RepositoryFolders
    {
        /// <summary>
        /// The DashboardFinanceAndOperationsAppFolder folder.
        /// </summary>
        [RepositoryFolder("be0234f2-9cd6-45e1-8197-580f1e1ad21e")]
        public partial class DashboardFinanceAndOperationsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _generalledgerInfo;
            RepoItemInfo _generaljournalsInfo;
            RepoItemInfo _clicknewbuttonInfo;
            RepoItemInfo _clickgeneratedlineInfo;

            /// <summary>
            /// Creates a new DashboardFinanceAndOperations  folder.
            /// </summary>
            public DashboardFinanceAndOperationsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DashboardFinanceAndOperations", "/dom[8]", parentFolder, 30000, null, false, "be0234f2-9cd6-45e1-8197-580f1e1ad21e", "")
            {
                _generalledgerInfo = new RepoItemInfo(this, "GeneralLedger", ".//div[#'mainPane']/div[3]//a[@innertext='General ledger']", 30000, null, "3d84d0b1-d05d-473f-8cf2-4f5ce3e06643");
                _generaljournalsInfo = new RepoItemInfo(this, "GeneralJournals", ".//div[#'mainPane']/div[3]/div/div[2]/div/div/div[4]/a[@innertext='General journals']", 30000, null, "7e76c4e3-ac3d-4e46-9630-a23934fb8fff");
                _clicknewbuttonInfo = new RepoItemInfo(this, "ClickNewButton", ".//span[#'ledgerjournaltable3_2_SystemDefinedNewButton_label']", 30000, null, "4d9d17a1-9a55-4266-9831-6f6a24b7a084");
                _clickgeneratedlineInfo = new RepoItemInfo(this, "ClickGeneratedLine", ".//input[#'ledgerjournaltable3_2_LedgerJournalTable_JournalNum_input']", 30000, null, "65f9d71b-0610-4821-8a1e-244b454632ce");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("be0234f2-9cd6-45e1-8197-580f1e1ad21e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("be0234f2-9cd6-45e1-8197-580f1e1ad21e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GeneralLedger item.
            /// </summary>
            [RepositoryItem("3d84d0b1-d05d-473f-8cf2-4f5ce3e06643")]
            public virtual Ranorex.ATag GeneralLedger
            {
                get
                {
                    return _generalledgerInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The GeneralLedger item info.
            /// </summary>
            [RepositoryItemInfo("3d84d0b1-d05d-473f-8cf2-4f5ce3e06643")]
            public virtual RepoItemInfo GeneralLedgerInfo
            {
                get
                {
                    return _generalledgerInfo;
                }
            }

            /// <summary>
            /// The GeneralJournals item.
            /// </summary>
            [RepositoryItem("7e76c4e3-ac3d-4e46-9630-a23934fb8fff")]
            public virtual Ranorex.ATag GeneralJournals
            {
                get
                {
                    return _generaljournalsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The GeneralJournals item info.
            /// </summary>
            [RepositoryItemInfo("7e76c4e3-ac3d-4e46-9630-a23934fb8fff")]
            public virtual RepoItemInfo GeneralJournalsInfo
            {
                get
                {
                    return _generaljournalsInfo;
                }
            }

            /// <summary>
            /// The ClickNewButton item.
            /// </summary>
            [RepositoryItem("4d9d17a1-9a55-4266-9831-6f6a24b7a084")]
            public virtual Ranorex.SpanTag ClickNewButton
            {
                get
                {
                    return _clicknewbuttonInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ClickNewButton item info.
            /// </summary>
            [RepositoryItemInfo("4d9d17a1-9a55-4266-9831-6f6a24b7a084")]
            public virtual RepoItemInfo ClickNewButtonInfo
            {
                get
                {
                    return _clicknewbuttonInfo;
                }
            }

            /// <summary>
            /// The ClickGeneratedLine item.
            /// </summary>
            [RepositoryItem("65f9d71b-0610-4821-8a1e-244b454632ce")]
            public virtual Ranorex.InputTag ClickGeneratedLine
            {
                get
                {
                    return _clickgeneratedlineInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ClickGeneratedLine item info.
            /// </summary>
            [RepositoryItemInfo("65f9d71b-0610-4821-8a1e-244b454632ce")]
            public virtual RepoItemInfo ClickGeneratedLineInfo
            {
                get
                {
                    return _clickgeneratedlineInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}