///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RegressionTest_v1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The validateLines recording.
    /// </summary>
    [TestModule("8a41319c-4881-4d16-8407-2ef3bd9b88eb", ModuleType.Recording, 1)]
    public partial class validateLines : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RegressionTest_v1Repository repository.
        /// </summary>
        public static RegressionTest_v1Repository repo = RegressionTest_v1Repository.Instance;

        static validateLines instance = new validateLines();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public validateLines()
        {
            channel = "10";
            tagMainAccount = "511151000";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static validateLines Instance
        {
            get { return instance; }
        }

#region Variables

        string _channel;

        /// <summary>
        /// Gets or sets the value of variable channel.
        /// </summary>
        [TestVariable("d3fc8bdf-0fcf-4409-8e18-68975b49c54b")]
        public string channel
        {
            get { return _channel; }
            set { _channel = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable tagMainAccount.
        /// </summary>
        [TestVariable("10973c08-5f6a-4440-afcc-da36a9e7f05f")]
        public string tagMainAccount
        {
            get { return repo.tagMainAccount; }
            set { repo.tagMainAccount = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
